//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manabi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendum
    {
        public int Id { get; set; }
        public Nullable<int> fk_pictograma { get; set; }
        public Nullable<int> hora { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> dia { get; set; }
    
        public virtual Dia Dia1 { get; set; }
        public virtual Hora Hora1 { get; set; }
        public virtual Pictograma Pictograma { get; set; }
    }
}
